services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: calculator_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  app:
    build: .
    command: python /app/app/main.py  
    environment:
      DB_HOST: db
      DB_NAME: calculator_db
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
